version: '3.8'
services:
  db:
    image: mongo:4.2.3-bionic
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
volumes:
  db:
    driver: local
